version: '3'

services:
  nest-app:
    image: nest-app:latest
    build:
      context: .
    environment:
      - DATABASE_HOST=db
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pass123
